.MODEL SMALL
.STACK 100H
.DATA
CR EQU 0DH
LF EQU 0AH 
C1 DB ?
MSG1 DB CR,LF,'ENTER A HEX DIGIT: ','$'
MSG2 DB CR,LF,'IN DECIMAL IT IS:$'
MSG3 DB CR,LF,'DO YOU WANT TO DO IT AGAIN: ','$'
MSG4 DB CR,LF,'ILLEGAL CHARACHTER $'
MSG5 DB CR,LF,'IN DECIMAL IT IS:1$'
.CODE

MAIN PROC 
  MOV AX,@DATA
  MOV DS,AX
BEGIN:
    MOV AH,09H
    LEA DX,MSG1
    INT 21H
NEW:
    MOV AH,01H
    INT 21H
    CMP AL,'0'
    JL ILLEGAL
    CMP AL,'9'
    JG ILLEGAL
    MOV CL,AL
    MOV AH,09H
    LEA DX,MSG2
    INT 21H
    MOV AH,02H
    MOV DL,CL
    INT 21H
    JMP AGAIN  
AGAIN:
    MOV AH,09H
    LEA DX,MSG3
    INT 21H 
    MOV AH,01H
    INT 21H
    CMP AL,'Y'
    JE BEGIN
    CMP AL,'N'
    JE EXIT
ILLEGAL:
     CMP AL,'A'
     JL ILLEGAL_FINAL
     CMP AL,'F'
     JG ILLEGAL_FINAL
     SUB AL,11H
     MOV BL,AL
     MOV AH,09H
     LEA DX,MSG5
     INT 21H
     MOV AH,02H
     MOV DL,BL 
     INT 21H 
     JMP AGAIN
ILLEGAL_FINAL:
     MOV AH,09H
     LEA DX,MSG4
     INT 21H
     JMP BEGIN    
EXIT:
    MOV AH,4CH
    INT 21H
        
    
    MAIN ENDP
END MAIN