.MODEL SMALL
.STACK 100H
.DATA
.CODE
MAIN PROC
    XOR CX,CX   ;CLEARING CX
    MOV AH,01H  ;TAKING INPUT
    INT 21H
    WHILE_:
        CMP AL,0DH
        JE END_WHILE    ;IF INPUT == NEWLINE THEN END_WHILE
        PUSH AX         ;PUSH VALUE OF AX TO STACK (MUST USE 16BIT REGISTER OR VAR)
        INC CX          ;CX IS USED AND INCREMENTED TO KNOW THE SIZE OF INPUT WHICH WILL BE USED IN LINE:26
        INT 21H
        JMP WHILE_
    END_WHILE:
        MOV AH,02H
        MOV DL,0DH
        INT 21H
        MOV DL,0AH
        INT 21H
        JCXZ EXIT     ;EXIT IF NO CHARACTERS
    TOP:
        POP DX
        INT 21H
        LOOP TOP
    EXIT:
        MOV AH,4CH
        INT 21H
    MAIN ENDP
END MAIN